windowrule {
  name        = Telegram

  group       = set
  match:class = ^(org.telegram.desktop)$
  workspace   = 9
}
windowrule {
  name        = DconfEditor

  group       = set
  match:class = ca.desrt.dconf-editor
  workspace   = 10
}
windowrule {
  name        = Discord

  group       = set
  match:class = discord
  workspace   = 9
}
windowrule {
  name        = ImageViewer

  float       = ON
  match:class = feh
}
windowrule {
  name        = VolumeControl

  match:class = org.pulseaudio.pavucontrol
  workspace   = 10
}
windowrule {
  name        = RemoteDesktop

  group       = set
  match:class = remmina
  workspace   = 5
}
windowrule {
  name        = Terminal

  match:class = ^(St)$
  workspace   = 2
}
windowrule {
  name        = Steam

  float       = ON
  match:class = steam
  workspace   = 4
}
windowrule {
  name        = VirtualMachine

  group       = set
  match:class = virt-manager
  workspace   = 5
}
windowrule {
  name        = WebBrowser

  match:class = zen
  workspace   = 3
}
