windowrule {
   name        = Conky
   
   float       = ON
   move        = 817 46
   size        = 330 862
   match:class = conky
   workspace   = special:magic silent
}

windowrule {
   name        = DconfEditor
   
   group       = set
   match:class = ca.desrt.dconf-editor
   workspace   = 10
}

windowrule {
   name        = Discord
   
   center      = on
   match:class = discord
   workspace   = 9
}

windowrule {
   name        = MakeMKV
   
   center      = on
   match:class = makemkv
   workspace   = 6
}

windowrule {
   name        = ImageViewer
   
   float       = ON
   match:class = feh
}

windowrule {
   name        = PasswordManager
   
   float       = ON
   match:class = org.keepassxc.KeePassXC
   move        = 1212 46
   size        = 800 823
   workspace   = special:magic silent
}

windowrule {
   name                = Steam
   
	match:title         = ^(Steam)$
	size                = 1285 854
   center              = ON
   float               = ON
   fullscreen_state    = 0
   match:initial_class = ^(steam)$
   workspace           = 5
}

windowrule {
   name                = SteamSettings
   
	float               = ON
   center              = ON
   match:initial_title = ^(Steam\sSettings)$
   size                = 1117 922
   workspace           = 5
}

windowrule {
   name                = WarFrame
   
   fullscreen_state    = 1
   match:initial_class = steam_app_230410
   workspace           = 6
}

windowrule {
   name                = Arc
   
   fullscreen_state    = 1
   match:initial_class = ^(steam_app_1808500)$
   workspace           = 6
}

windowrule {
   name        = Terminal
   
   match:class = St
   workspace   = 2
}

windowrule {
   name        = Teams
   
   match:class = teams-for-linux
   workspace   = 9
}

windowrule {
   name        = Telegram
   
   group       = set
   match:class = org.telegram.desktop
   workspace   = 9
}

windowrule {
   name        = VirtualMachine
   
   group       = set
   match:class = virt-manager
   workspace   = 5
}

windowrule {
   name        = VolumeControl
   
   match:class = org.pulseaudio.pavucontrol
   workspace   = 10
}

windowrule {
   name        = ZenBrowser
   
   match:class = zen
   workspace   = 3
}

windowrule {
   name        = BraveBrowser
   
   match:class = brave-browser
   workspace   = 3
}

windowrule {
   name        = VideoPlayer
   
   match:class = vlc
   workspace   = 5
}