windowrule {
	name        = Conky
	
	float       = ON
	move        = 817 46
	size        = 330 862
	match:class = conky
	workspace   = special:magic silent
}

windowrule {
	name        = DconfEditor
	
	group       = set
	match:class = ca.desrt.dconf-editor
	workspace   = 10
}

windowrule {
	name        = Discord
	
	group       = set
	match:class = discord
	workspace   = 9
}

windowrule {
	name        = ImageViewer
	
	float       = ON
	match:class = feh
}

windowrule {
	name        = PasswordManager
	
	float       = ON
	match:class = org.keepassxc.KeePassXC
	move        = 1212 46
	size        = 800 823
	workspace   = special:magic silent
}

windowrule {
	name                = RemoteDesktop
	
	fullscreen_state    = 0
	group               = set
	match:initial_class = ^(org.remmina.Remmina)$
	workspace           = 5
}

windowrule {
	name        = Terminal
	
	match:class = St
	workspace   = 2
}

windowrule {
	name        = Teams
	
	match:class = teams-for-linux
	workspace   = 9
}

windowrule {
	name        = Telegram
	
	group       = set
	match:class = org.telegram.desktop
	workspace   = 9
}

windowrule {
	name        = VirtualMachine
	
	group       = set
	match:class = virt-manager
	workspace   = 5
}

windowrule {
	name        = VolumeControl
	
	match:class = org.pulseaudio.pavucontrol
	workspace   = 10
}

windowrule {
	name        = WebBrowser
	
	match:class = zen
	workspace   = 3
}
