preload   = /home/eeccher/.local/etc/xdg/wp/dark_rock.jpg
preload   = /home/eeccher/.local/etc/xdg/wp/dark_rock_left.jpg
preload   = /home/eeccher/.local/etc/xdg/wp/dark_rock_right.jpg

wallpaper {
  monitor  = DP-1
  path     = $HOME/.local/etc/xdg/wp/dark_rock.jpg
  fit_mode = cover
}

wallpaper {
  monitor  = DP-4
  path     = $HOME/.local/etc/xdg/wp/dark_rock_left.jpg
  fit_mode = cover
}

wallpaper {
  monitor  = DP-2
  path     = $HOME/.local/etc/xdg/wp/dark_rock_right.jpg
  fit_mode = cover
}

splash    = true
# ipc     = off
