# ipc     = of
fsplash    = true
preload   = ~/.local/etc/xdg/hypr/wp/dark_rock.jpg
preload   = ~/.local/etc/xdg/hypr/wp/dark_rock_left.jpg
preload   = ~/.local/etc/xdg/hypr/wp/dark_rock_right.jpg

wallpaper {
  monitor  = DP-4
  path     = ~/.local/etc/xdg/hypr/wp/dark_rock.jpg
  fit_mode = cover
}

wallpaper {
  monitor  = DP-7
  path     = ~/.local/etc/xdg/hypr/wp/dark_rock_left.jpg
  fit_mode = cover
}

wallpaper {
  monitor  = DP-5
  path     = ~/.local/etc/xdg/hypr/wp/dark_rock_right.jpg
  fit_mode = cover
}
